---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.10
    env:
      TZ: ${TIMEZONE}
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Jellyfin
          hajimari.io/icon: simple-icons:jellyfin
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      nfs-media:
        enabled: true
        mountPath: /media
        path: /volume1/kubeNFS/torrents
        server: "${STORAGE_NAS_IP}"
        type: nfs
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 1Gi
