---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@hourly"
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/onedr0p/alpine
      tag: 3.19.1
    command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
    env:
      - name: CLOUDFLARE_EMAIL
        valueFrom:
          secretKeyRef:
            name: cluster-secrets
            key: SECRET_CLOUDFLARE_EMAIL
      - name: CLOUDFLARE_APIKEY
        valueFrom:
          secretKeyRef:
            name: cluster-secrets
            key: CLOUDFLARE_APIKEY
      - name: CLOUDFLARE_RECORD_NAME
        valueFrom:
          secretKeyRef:
            name: cluster-secrets
            key: CLOUDFLARE_DDNS_RECORD
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: cloudflare-ddns-configmap
        subPath: cloudflare-ddns.sh
        mountPath: /app/cloudflare-ddns.sh
        defaultMode: 0775
        readOnly: true
