---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: reflector
      version: 7.0.183
      sourceRef:
        kind: HelmRepository
        name: chart-emberstack
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: reflector
