---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform"

tasks:
  terraform:talos:init:
    desc: Initialize Terraform for the Talos cluster workspace
    dir: terraform/talos
    cmds:
      - terraform init {{.CLI_ARGS}}

  terraform:talos:plan:
    desc: Plan Terraform changes for the Talos cluster
    dir: terraform/talos
    cmds:
      - terraform plan {{.CLI_ARGS}}

  terraform:talos:apply:
    desc: Apply Terraform changes for the Talos cluster
    dir: terraform/talos
    cmds:
      - terraform apply {{.CLI_ARGS}}

  terraform:talos:destroy:
    desc: Destroy Terraform-managed Talos cluster resources
    dir: terraform/talos
    cmds:
      - terraform destroy {{.CLI_ARGS}}

  terraform:cloudflare:init:
    desc: Initialize Terraform for the Cloudflare workspace
    dir: terraform/cloudflare
    cmds:
      - terraform init {{.CLI_ARGS}}

  terraform:cloudflare:plan:
    desc: Plan Terraform changes for Cloudflare
    dir: terraform/cloudflare
    cmds:
      - terraform plan {{.CLI_ARGS}}

  terraform:cloudflare:apply:
    desc: Apply Terraform changes for Cloudflare
    dir: terraform/cloudflare
    cmds:
      - terraform apply {{.CLI_ARGS}}
