bpf:
  hostLegacyRouting: true
cluster:
  name: default
cni:
  customConf: true
  uninstall: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.40.0.0/16
k8sServiceHost: 192.168.100.9
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 1
  unmanagedPodWatcher:
    restart: false
policyEnforcementMode: never
routingMode: tunnel
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: vxlan
tunnelPort: 8473
tunnelProtocol: vxlan

