---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
