---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: ""
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  mountOptions:
    - local_lock=posix
    - nfsvers=4.1
  nfs:
    server: "${STORAGE_NAS_IP}"
    path: "volume1/kubeNFS/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T
