---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: media
spec:
  storageClassName: nextcloud-storageclass
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: "${STORAGE_NAS_IP}"
    path: "/volume1/kubeNFS/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-storageclass
  resources:
    requests:
      storage: 1T
