---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - local_lock=posix
    - nfsvers=4.1
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1T
