---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
