---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: media
spec:
  timeout: 15m
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.6.3
      sourceRef:
        kind: HelmRepository
        name: chart-nextcloud
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: postgresql
      namespace: database
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: "${REDIS_HOST_ADDRESS}"
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          value: ""
      securityContext:
        runAsUser: 1024
        runAsGroup: 100
        runAsNonRoot: true
      host: &host cloud.${SECRET_DOMAIN}
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "${POSTGRES_HOST_ADDRESS}:5432"
      database: nextcloud
      user: "postgres"
      password: "${SECRET_POSTGRES_ADMIN_PASS}"
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"
        hajimari.io/icon: mdi:dropbox
        nginx.ingress.kubernetes.io/proxy-body-size: "6G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data

