---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 4.6.3
      sourceRef:
        kind: HelmRepository
        name: chart-nextcloud
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: postgresql
      namespace: database
  # See https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml
  values:
    image:
      repository: docker.io/library/nextcloud
      tag: 28.0.2@sha256:00a5983ec3353ed71df9c6df644a84c3d8a88ac7b93d8f591fdcbb5eaa8fb459

    env:
      PHP_MEMORY_LIMIT: 256M

    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:nextcloud
        hajimari.io/info: File and Calendar server
        hajimari.io/group: tools
        external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"

      tls:
      - hosts:
        - cloud.${SECRET_DOMAIN}
    redis:
      enabled: false
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "${POSTGRES_HOST_ADDRESS}:5432"
      database: nextcloud
      user: "postgres"
      password: "${SECRET_POSTGRES_ADMIN_PASS}"
    cronjob:
      enabled: true
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1

    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
          default_phone_region = RO
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array(
               0 => '10.40.0.0/8',
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
          );
        gitops.config.php: |-
          <?php
          $CONFIG = array (
            'appstoreenabled' => true,
            #'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
          );
        bulkupload.config.php: |-
          <?php
          $CONFIG = array (
            'bulkupload.enabled' => false,
          );

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false

    persistence:
      enabled: true
      existingClaim: "nextcloud-config"
      nextcloudData:
        enabled: true
        existingClaim: "nextcloud-data"
