---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 1.7.5
      sourceRef:
        kind: HelmRepository
        name: chart-fairwinds
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 0.14.0
      extraArgs:
        prometheus-address: |
          http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        storage: prometheus
      resources:
        requests:
          cpu: 15m
          memory: 105M
    updater:
      enabled: false
    admissionController:
      enabled: false
