---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: chart-nfs-subdir-external-provisioner
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  values:
    args:
    nfs:
      server: "${STORAGE_NAS_IP}"
      path: /volume1/kubeNFS
