---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
