---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guacamole
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/flcontainers/guacamole
      tag: 1.5.4
    env:
      TZ: "${TIMEZONE}"
      EXTENSIONS: auth-ldap
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        memory: 500Mi
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.100.49"
        externalIPs: ["192.168.100.49"]
        ports:
          bittorrent:
            enabled: true
            port: 3389
            protocol: TCP
            targetPort: 3389
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Guacamole
          hajimari.io/icon: cbi:guacamole
          external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"

        hosts:
          - host: &host remote.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: guacamole-config
        mountPath: /config

