---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: chart-fairwinds
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
        limits:
          memory: 210M
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Goldilocks
          gethomepage.dev/icon: mdi-align-vertical-top
        hosts:
          - host: &host goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          memory: 210M
