---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 18.17.0
      sourceRef:
        kind: HelmRepository
        name: chart-bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: "standalone"
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    sentinel:
      enabled: false
