---
apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap
  namespace: database
  annotations:
    io.cilium/lb-ipam-ips: "${LDAP_OUTPOST_IP}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 3389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 6636
  selector:
    app.kubernetes.io/name: authentik-outpost-ldap
    goauthentik.io/outpost-name: ldap-outpost
    goauthentik.io/outpost-type: ldap
