---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  values:
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.8.1
    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 5055
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Jellyseerr
          hajimari.io/icon: mdi:jellyfish-outline
          external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"

        hosts:
          - host: &host jellyseerr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config
        mountPath: /app/config
    resources:
      requests:
        cpu: 30m
        memory: 60Mi
      limits:
        memory: 500Mi
        cpu: 400m
