---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-github-alerts
  namespace: flux-system
spec:
  providerRef:
    name: github-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
