---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-provider
  namespace: flux-system
spec:
  type: github
  address: https://api.github.com
  secretRef:
    name: github-token
