apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns
    namespace: kube-system
data:
    Corefile: ENC[AES256_GCM,data:b7f0hekasktIo8hL9cnvU4mnqBjE716dnqV9LtL1t+fbtqrf7UwJLsK/729n5ZdUmS/0U0wJ+Hj1/lRLNdKXfM+XnnjJNgdWSMssvxHtCW9jIsFx8Ajk/TNtUoRI8XHVRVKPSSjE3037PJYwq7jVIyCnCSFgx/Wy9/06vbjgSkgiSRxIZWVmiipAMcLkW9XKY0kNFLMgYQpQ++U0pJcWqcrZbOgcoTJ2KXsKlSIGW8zs7NW7Pdcj7TlKyhlUbr6YniQ0lW85ZQixt4KhcXWq6Wuvu+DsN5iyZAT7BMBoXvbmhUPoXaxGy+63y5WEW7PH5/gJ1Wr8XMLPn5tuN9hMb75ifdw46Nm1Qhr7zCST/0rHaNl4LpBF3wZ7Uu6HOnFGPLbRFcoiXmRH5A6WotzfJhdrhHzXYOGzPd/FUddGQtUqfuC35QkooHjKq1ZeRCMaFVz96EmMjL1JTml5Ya6OaI1Tyt214fU9VhPri9tJRrVGX+8HRh7UrgaDBIh7tu4iUnanARQko6iMGG1qA/Uok2femjoPD2eNfVTwWGuprFUzKTjQojL2C/0=,iv:Pd2NS4g3L7QFFSBo7IzrcmL5TVWzsL+ki0PaV7GEtXs=,tag:97QlxXNXxHv3DgeCCpALcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSGJZQXhiMm1BQ2toTjRu
            MkFxU3ZZeW9uZ3NiTTNRZkxsNWNqM0FyWEhFCmZxRU9hWnBLOW9hVENJdlhlbnJx
            Zlp6cmh0RTJidVNYMkh6cVQvTk9pakUKLS0tIC9tSTZlU2ZYV05nUjVmN3ZRcU1w
            c0U2QkJKc20ydUZ0Q0VCZXVOWVFObHMKBSHdvPQmn0dUWBlJzLSr3HD8bOfwPcNw
            dw1oMaEJvQrLU/ppgYNO5JAHOtN2cX3A/1UFCdzUWw2rauLoRlLDkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T09:20:10Z"
    mac: ENC[AES256_GCM,data:NA6sxn/l0TZSIU5xlnN2RIt+0nipIqH6/aJ/fgXKaOoNDT/52nOj/MXYTe6Wdn6omi4TVXTsixmGtauc1R+hLtw0wCN/L7ufAczaU8VejCC/OqM4BVTWgba8eLONQl83V/P+eyZKlcNZp1UR5OtoAxb/3vvaoUvs+NR0sFXRdGU=,iv:pmBPq7gTm8VaamoxUMuiVRIq39DIU+LxJjFtMOo1GKs=,tag:3PsLRvW9fagjrjXfkE4R2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
