apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns
    namespace: kube-system
data:
    Corefile: ENC[AES256_GCM,data:MfeS4saUAE9DyhFWkEv2HCXyvbLal6T0RE3KgU9ISzfeSV4ce1QlHs7VSD7phB+sUI+GZviMb8MYpxLTTMiby6vdprXvLdIO627mvpmD/tydimQSOlurIyaqheMycAbQx+1nQcu//xl5mGq+rUnpEwYpxIBAVrcEIsJCLbveqALg3cklQAljxTKYW7nKp0yRsf18Hh6hdGHAViAGEgraowt5ZRUUHfRQEha7axEP2dzeT8nyop70LjPYn5XtNRrO68lcjIoGYSEr/QcYiHQitp+LFe229FVZhkWnZrnQOExsvruyOxDCINnw3wy8dwVFg3FfCZhMvYhkv5n8e1L4vE2Ki/4aMBf949Bx4uVLZQPpfrDJsi+Ob+BHc4LublCldaBq1dZVNwkQM74lNZxIBG8RbKiftt7aHIUDumpaTWdOI5FGB16NZckRRWryYX5ChSzBLzz2wERJjcJn1845g5fHcmKLkTkDRCakf0RS2jmQxpe6SY7FUNNNSFZGU4hlDhHTxccEJeTGWS/O1DYKKU0FciPtIRftlwN1wogC41NGPeZ5eX0=,iv:Y2xLlQmtr1zPCaN6PCSkHN6KYAvdhTffPeMS2Cw7tOQ=,tag:SReH7edZBXxqTr+NgRkfeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSGJZQXhiMm1BQ2toTjRu
            MkFxU3ZZeW9uZ3NiTTNRZkxsNWNqM0FyWEhFCmZxRU9hWnBLOW9hVENJdlhlbnJx
            Zlp6cmh0RTJidVNYMkh6cVQvTk9pakUKLS0tIC9tSTZlU2ZYV05nUjVmN3ZRcU1w
            c0U2QkJKc20ydUZ0Q0VCZXVOWVFObHMKBSHdvPQmn0dUWBlJzLSr3HD8bOfwPcNw
            dw1oMaEJvQrLU/ppgYNO5JAHOtN2cX3A/1UFCdzUWw2rauLoRlLDkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T09:24:09Z"
    mac: ENC[AES256_GCM,data:PUkQI3Q0sq/M6CN1psy6u93kbWFAIJggC2dI4DmB/M3NDj4FlkDFvXCx7ZQ5Licv59LZZoSFiNpCDvwDSkfcJa64XCrNZVMBPyPyTyhV4ZdpKGOWXz16mCjYEbH8YV/0UuXyJtqo8h338fnIvKswdCpfTjJsGfxzrJg2MnDl0G4=,iv:E/ODNLQiqhWQr6EoyAJwsyXan5TZMq6+WP9+/i+f2mU=,tag:57ujFhgvEfoLgDv/yJSDFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
