---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: prowlarr
      namespace: media
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.5.2.7388
    env:
      TZ: ${TIMEZONE}
      RADARR__LOG_LEVEL: info
      RADARR__BRANCH: master
      RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
      RADARR__POSTGRES_HOST: "${POSTGRES_HOST_ADDRESS}"
      RADARR__POSTGRES_USER: "postgres"
      RADARR__POSTGRES_PASSWORD: "${SECRET_POSTGRES_ADMIN_PASS}"
      RADARR__POSTGRES_MAIN_DB: radarr-main
      RADARR__POSTGRES_LOG_DB: radarr-log
      RADARR__API_KEY: "${RADARR_SECRET_KEY}"
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: radarr
          hajimari.io/icon: filmstrip
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config

      media:
        enabled: true
        mountPath: /downloads
        path: /volume1/kubeNFS/torrents
        server: "${STORAGE_NAS_IP}"
        type: nfs

    resources:
      requests:
        cpu: 15m
        memory: 380M
      limits:
        cpu: 100m
        memory: 670M
