---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  values:
    hostname: radarr

    controllers:
      main:
        enabled: true

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/radarr
          tag: 5.2.6.8376
        env:
          - name: TZ
            value: ${TIMEZONE}
          - name: RADARR__LOG_LEVEL
            value: info
          - name: RADARR__BRANCH
            value: master
          - name: RADARR__APPLICATION_URL
            value: "https://radarr.${SECRET_DOMAIN}"
          - name: RADARR__POSTGRES_HOST
            value: "${POSTGRES_HOST_ADDRESS}"
          - name: RADARR__POSTGRES_USER
            value: "postgres"
          - name: RADARR__POSTGRES_PASSWORD
            value: "${SECRET_POSTGRES_ADMIN_PASS}"
          - name: RADARR__POSTGRES_MAIN_DB
            value: radarr-main
          - name: RADARR__POSTGRES_LOG_DB
            value: radarr-log
          - name: RADARR__API_KEY
            value: "${RADARR_SECRET_KEY}"
        resources: {}

    services:
      main:
        ports:
          http:
            port: 7878

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: radarr
          gethomepage.dev/icon: filmstrip
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      enabled: true
      items:
        - name: config
          type: pvc
          existingClaim: radarr-config
          mountPath: /config
        - name: media
          type: nfs
          mountPath: /downloads
          path: /volume1/kubeNFS/torrents
          server: "${STORAGE_NAS_IP}"

    resources:
      requests:
        cpu: 15m
        memory: 380Mi
      limits:
        cpu: 500m
        memory: 970Mi
