---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radarr
  namespace: media
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 30s
