---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.5.0.3390
    hostname: prowlarr
    env:
      TZ: ${TIMEZONE}
      PROWLARR__LOG_LEVEL: info
      PROWLARR__BRANCH: nightly
      PROWLARR__APPLICATION_URL: "https://prowlarr.${SECRET_DOMAIN}"
      PROWLARR__POSTGRES_HOST: "${POSTGRES_HOST_ADDRESS}"
      PROWLARR__POSTGRES_MAIN_DB: prowlarr-main
      PROWLARR__POSTGRES_LOG_DB: prowlarr-log
      PROWLARR__POSTGRES_USER: "postgres"
      PROWLARR__POSTGRES_PASSWORD: "${SECRET_POSTGRES_ADMIN_PASS}"
      PROWLARR__PORT: &port 9696
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Prowlarr
          hajimari.io/icon: mdi:cat
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v2
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 300Mi
        cpu: 200m
