---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: postgresql
      namespace: database
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      prowlarr:
        pod:
          hostname: prowlarr
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/prowlarr-develop
              tag: 1.32.2.4987
            env:
              TZ: ${TIMEZONE}
              PROWLARR__LOG_LEVEL: info
              PROWLARR__BRANCH: develop
              PROWLARR__APPLICATION_URL: "https://prowlarr.${SECRET_DOMAIN}"
              PROWLARR__POSTGRES_HOST: "${POSTGRES_HOST_ADDRESS}"
              PROWLARR__POSTGRES_MAIN_DB: prowlarr-main
              PROWLARR__POSTGRES_LOG_DB: prowlarr-log
              PROWLARR__POSTGRES_USER: "postgres"
              PROWLARR__POSTGRES_PASSWORD: "${SECRET_POSTGRES_ADMIN_PASS}"
              PROWLARR__PORT: &port 9696
              PROWLARR__API_KEY: "${PROWLARR_SECRET_KEY}"
            resources:
              requests:
                cpu: 15m
                memory: 220Mi
              limits:
                memory: 350Mi
          metrics:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.2.0
            args: ["prowlarr"]
            env:
              PORT: &metrics-port 9708
              URL: "http://localhost:9696"
              APIKEY: "${PROWLARR_SECRET_KEY}"
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: *port
          metrics:
            port: *metrics-port
    ingress:
      prowlarr:
        className: traefik
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: prowlarr-config-v2
        globalMounts:
          - path: /config
