---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-client
