---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent:
        pod:
          hostname: qbittorrent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.1
            env:
              TZ: ${TIMEZONE}
              QBITTORRENT__PORT: &port 8080
              QBITTORRENT__BT_PORT: &port-bt 18289
    
    service:
      qbittorrent:
        controller: qbittorrent
        ports:
          http:
            port: *port
      bittorrent:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${QBITTORRENT_IP}"
        externalIPs: ["${QBITTORRENT_IP}"]
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt
        externalTrafficPolicy: Local
    
    persistence:
      config:
        existingClaim: qbitorrent-config
        globalMounts:
          - path: /config
      downloads:
        type: nfs
        server: "${STORAGE_NAS_IP}"
        path: /volume1/kubeNFS/torrents
        globalMounts:
          - path: /downloads
