---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 52.1.0
      sourceRef:
        kind: HelmRepository
        name: chart-prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 5
      remediateLastFailure: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    cleanPrometheusOperatorObjectNames: true
    kubeControllerManager:
      enabled: true
      endpoints: ["192.168.100.10"]
    kubeScheduler:
      enabled: true
      endpoints: ["192.168.100.10"]
    coreDns:
      enabled: true
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeDns:
      enabled: false
    kubeApiServer:
      enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
    nodeExporter:
      enabled: true
    prometheusOperator:
      resources:
        requests:
          cpu: 25m
          memory: 250Mi
        limits:
          cpu: 50m
          memory: 400Mi
    prometheus-node-exporter:
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 150m
          memory: 250M
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        annotations:
          hajimari.io/appName: Prometheus
          hajimari.io/icon: simple-icons:prometheus
        hosts:
          - &pmhost prometheus.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *pmhost
      prometheusSpec:
        enableAdminAPI: true
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        walCompression: true
        retention: 7d
        retentionSize: "4GB"
        resources:
          requests:
            cpu: 150m
            memory: 2500Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        inhibit_rules:
          - source_matchers:
              - 'severity = critical'
            target_matchers:
              - 'severity =~ warning|info'
            equal:
              - 'namespace'
              - 'alertname'
          - source_matchers:
              - 'severity = warning'
            target_matchers:
              - 'severity = info'
            equal:
              - 'namespace'
              - 'alertname'
          - source_matchers:
              - 'alertname = InfoInhibitor'
            target_matchers:
              - 'severity = info'
            equal:
              - 'namespace'
        route:
          group_by: ['namespace']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: discord
          routes:
            - receiver: 'null'
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
        receivers:
          - name: 'null'
          - name: discord
            discord_configs:
              - webhook_url: ${SECRET_PROMETHEUS_DISCORD_WEBHOOK}
                title: |-
                  [{{ .Status | toUpper }}:{{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else }}{{ .Alerts.Resolved | len }}{{ end }}]
                message: |-
                  {{- range .Alerts }}
                    **{{ .Labels.alertname }} {{ if ne .Labels.severity "" }}({{ .Labels.severity | title }}){{ end }} **
                    {{- if ne .Annotations.description "" }}
                      **Description:** {{ .Annotations.description }}
                    {{- else if ne .Annotations.summary "" }}
                      **Summary:** {{ .Annotations.summary }}
                    {{- else if ne .Annotations.message "" }}
                      **Message:** {{ .Annotations.message }}
                    {{- else }}
                      **Description:** N/A
                    {{- end }}
                  {{- end }}
        templates:
          - '/etc/alertmanager/config/*.tmpl'
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "Alert Manager"
          hajimari.io/icon: mdi:alert-decagram-outline
        hosts:
          - &amhost alertmanager.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *amhost
      alertmanagerSpec:
        resources:
          requests:
            cpu: 11m
            memory: 53M
          limits:
            cpu: 23m
            memory: 105M
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 100Mi
