---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: metallb-system
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: chart-dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    resources:
      - apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: l2-ip
          namespace: metallb-system
        spec:
          ipAddressPools:
            - default-pool

      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default-pool
          namespace: metallb-system
        spec:
          addresses:
            - "${METALLB_LB_RANGE}"
