---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  annotations:
    reloader.stakater.com/match: "true"
data:
  bookmarks.yaml: |
    ---
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - Hackaday:
            - abbr: GH
              href: https://hackaday.com/blog
        - Hackernews:
            - abbr: HN
              href: https://news.ycombinator.com
    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    ---
    - Media:
        - Jellyfin:
            href: https://jellyfin.${SECRET_DOMAIN}
            icon: si-jellyfin
        - Music:
            href: https://music.${SECRET_DOMAIN}
            icon: si-jellyfin
        - Photos:
            href: https://photos.${SECRET_DOMAIN}
            icon: si-jellyfin
        - Drive:
            href: https://drive.${SECRET_DOMAIN}
            icon: si-jellyfin
    - Downloads:
        - qBitTorrent:
            href: https://qbittorrent.${SECRET_DOMAIN}
            icon: mdi-cloud-download
    - Media Automation:
        - Prowlarr:
            href: https://prowlarr.${SECRET_DOMAIN}
            icon: mdi-cat
            widget:
              type: prowlarr
              url: http://prowlarr.media.svc.cluster.local:9696
              key: ${PROWLARR_SECRET_KEY}
        - Radarr:
            href: https://radarr.${SECRET_DOMAIN}
            icon: filmstrip
            widget:
              type: radarr
              url: http://radarr.media.svc.cluster.local:7878
              key: ${RADARR_SECRET_KEY}
        - Jellyseerr:
            href: https://jellyseerr.${SECRET_DOMAIN}
            icon: mdi-jellyfish-outline
    - Storage:
        - Longhorn:
            href: https://longhorn.${SECRET_DOMAIN}
            icon: mdi-harddisk
        - Synology:
            href: http://${STORAGE_NAS_IP}:5000
            description: Synology NAS
            icon: si-synology
    - Security:
        - Authentik:
            href: https://auth.${SECRET_DOMAIN}
            icon: si-webauthn
    - Monitoring:
        - Goldilocks:
            href: https://goldilocks.${SECRET_DOMAIN}
            icon: mdi-align-vertical-top
    - Database:
        - PGAdmin:
            href: https://pgadmin.${SECRET_DOMAIN}
            icon: bxl:postgresql
  widgets.yaml: |
    ---
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Ciau!"
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        # Show the expanded
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: false
  kubernetes.yaml: |
    ---
    mode: cluster
  docker.yaml: |
    ---
  settings.yaml: |
    ---
    title: Dashboard
    favicon: https://kubernetes.io/images/favicon.png
    theme: dark
    color: stone
    target: _self
    headerStyle: clean
    allowedHosts: home.${SECRET_DOMAIN}
    layout:
      Media:
        style: row
        columns: 4
      Downloads:
        style: row
        columns: 1
      Media Automation:
        style: row
        columns: 3
      Storage:
        style: row
        columns: 2
      Security:
        style: row
        columns: 1
      Monitoring:
        style: row
        columns: 1
      Database:
        style: row
        columns: 1
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
