---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 14.3.3
      sourceRef:
        kind: HelmRepository
        name: chart-bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 16.6.0
    auth:
      enablePostgresUser: true
      postgresPassword: ${SECRET_POSTGRES_ADMIN_PASS}
      database: postgres
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-data
