---
# (string) The ARP address kube-vip broadcasts
# Used to load balance control plane nodes
kubevip_address: "192.168.100.9"
# CIDR used for calico installation of where to look for nodes
calico_cidr: "192.168.100.0/24"

# (string) Timezone for the servers
timezone: "Europe/Bucharest"

apt_packages:
  - htop
  - lm-sensors
  - nfs-common
  - open-iscsi
  - python3-yaml
  - python3-kubernetes

#
# Below vars are for the xanmanning.k3s role
# https://github.com/PyratLabs/ansible-role-k3s
#
# (string) Use a specific version of k3s
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.30.3+k3s1"
# (bool) Install using hard links rather than symbolic links.
k3s_install_hard_links: true
# (bool) Escalate user privileges for all tasks
k3s_become: true
# (bool) Enable debug logging on the k3s service
k3s_debug: false
# (bool) Enable etcd embedded datastore
k3s_etcd_datastore: true
# (bool) Allow the use of unsupported configurations in k3s
k3s_use_unsupported_config: true
# (string) Control Plane registration address
k3s_registration_address: "{{ kubevip_address }}"
# (list) A list of URLs to deploy on the primary control plane. Read notes below.
k3s_server_manifests_urls:
  # Kube-vip
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
  # Tigera Operator
  - url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
    filename: calico-tigera-operator.yaml

# (list) A flat list of templates to deploy on the primary control plane
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - calico-installation.yaml.j2
  - kube-vip-daemonset.yaml.j2
