---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qbittorrent
  - prowlarr
  - jellyseerr
  - radarr
  - sonarr
  - jellyfin
  - flaresolverr
  - guacamole
  - nextcloud
  - nextology
