---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-config
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
