---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: plan-worker
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.30.4+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - plan-master
    image: rancher/k3s-upgrade
  upgrade:
    image: rancher/k3s-upgrade
