---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: chart-external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: 2m
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cluster-secrets
            key: SECRET_CLOUDFLARE_EMAIL
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cluster-secrets
            key: CLOUDFLARE_APIKEY
    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns.alpha.kubernetes.io/target
    policy: sync
    sources: ["ingress"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-secrets
